/* =========================
   CREATE TABLE - 생성 순서
   부모 테이블 먼저 생성
========================= */

CREATE TABLE admin (
                       admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       admin_username VARCHAR2(50) NOT NULL UNIQUE,
                       admin_password VARCHAR2(255) NOT NULL,
                       admin_email VARCHAR2(100) NOT NULL UNIQUE,
                       admin_role VARCHAR2(20) DEFAULT '관리자' NOT NULL,
                       admin_created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                       admin_last_login TIMESTAMP,
                       admin_status VARCHAR2(10) DEFAULT '활성' NOT NULL
);
CREATE TABLE advertisements (
                                adv_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                adv_order NUMBER NOT NULL UNIQUE,
                                adv_title VARCHAR2(100),
                                adv_image_url VARCHAR2(255),
                                adv_created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                                adv_updated_at TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE member (
                        mem_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_userid VARCHAR2(100) NOT NULL UNIQUE,
                        mem_email VARCHAR2(255) NOT NULL,
                        mem_password VARCHAR2(255),
                        mem_username VARCHAR2(100) NOT NULL,
                        mem_nickname VARCHAR2(100),
                        mem_phone VARCHAR2(20),
                        mem_birthday DATE,
                        mem_gender VARCHAR2(10),
                        mem_point NUMBER(10) DEFAULT 0 NOT NULL,
                        mem_grade VARCHAR2(10) NOT NULL,
                        mem_address VARCHAR2(255),
                        mem_register_ip VARCHAR2(50) NOT NULL,
                        mem_lastlogin_ip VARCHAR2(50),
                        mem_register_date TIMESTAMP DEFAULT SYSDATE,
                        mem_lastlogin_date TIMESTAMP DEFAULT SYSDATE,
                        mem_status VARCHAR2(10) NOT NULL,
                        mem_receive_email VARCHAR2(10) NOT NULL,
                        mem_open_profile VARCHAR2(10) NOT NULL,
                        mem_receive_notify VARCHAR2(10) NOT NULL,
                        mem_login_type VARCHAR2(20)
);

CREATE TABLE pre_member (
                            pre_mem_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            pre_mem_biz_reg_no VARCHAR2(30) NOT NULL,
                            pre_mem_ceo_name VARCHAR2(50) NOT NULL,
                            pre_mem_phone VARCHAR2(20),
                            pre_mem_user_id VARCHAR2(50) NOT NULL,
                            pre_mem_password VARCHAR2(200) NOT NULL,
                            pre_mem_email VARCHAR2(100) NOT NULL,
                            pre_mem_biz_license_photo VARCHAR2(300),
                            pre_mem_created_at TIMESTAMP,
                            pre_mem_updated_at TIMESTAMP,
                            pre_mem_status VARCHAR2(10),
                            pre_mem_approval_status VARCHAR2(10)
);

CREATE TABLE riders (
                        rider_No NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        rider_id VARCHAR2(50) NOT NULL UNIQUE,
                        rider_pw VARCHAR2(100),
                        rider_name VARCHAR2(50),
                        rider_phone VARCHAR2(20),
                        vehicle_type VARCHAR2(20),
                        rider_gender VARCHAR2(20),
                        rider_birth DATE,
                        rider_created_at TIMESTAMP,
                        total_deliveries NUMBER,
                        is_available VARCHAR2(10) NOT NULL
);

CREATE TABLE coupons (
                         cpn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cpn_code VARCHAR2(255) NOT NULL UNIQUE,
                         cpn_name VARCHAR2(255) NOT NULL,
                         cpn_content VARCHAR2(255) NOT NULL,
                         cpn_deduct_price NUMBER NOT NULL,
                         cpn_min_price NUMBER NOT NULL,
                         cpn_order_type VARCHAR2(255) NOT NULL,
                         cpn_status VARCHAR2(255) NOT NULL,
                         cpn_created TIMESTAMP DEFAULT SYSDATE NOT NULL,
                         cpn_modified TIMESTAMP DEFAULT SYSDATE NOT NULL,
                         cpn_expired TIMESTAMP NOT NULL
);

CREATE TABLE boards (
                        board_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_id NUMBER NOT NULL,
                        board_title VARCHAR2(255),
                        board_content VARCHAR2(255),
                        board_createdAt TIMESTAMP DEFAULT SYSDATE,
                        board_updatedAt TIMESTAMP,
                        board_answer_status VARCHAR2(255)
);

CREATE TABLE notifications (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               sender_type VARCHAR2(50),
                               sender_id NUMBER,
                               recipient_type VARCHAR2(50) NOT NULL,
                               recipient_id NUMBER NOT NULL,
                               category VARCHAR2(50) NOT NULL,
                               message VARCHAR2(255) NOT NULL,
                               created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                               status VARCHAR2(50) DEFAULT '읽지 않음' NOT NULL
);

CREATE TABLE pre_store (
                           pre_sto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           pre_sto_pre_mem_id NUMBER NOT NULL,
                           pre_sto_name VARCHAR2(100) NOT NULL,
                           pre_sto_category VARCHAR2(50),
                           pre_sto_address VARCHAR2(200),
                           pre_sto_photo VARCHAR2(300),
                           pre_sto_phone VARCHAR2(20),
                           pre_sto_intro VARCHAR2(1000),
                           pre_sto_min_order_amount NUMBER,
                           pre_sto_delivery_fee NUMBER,
                           pre_sto_delivery_time_min NUMBER,
                           pre_sto_delivery_time_max NUMBER,
                           pre_sto_rating NUMBER(3,1) NOT NULL,
                           pre_sto_review_count NUMBER NOT NULL,
                           pre_sto_created_at TIMESTAMP,
                           pre_sto_updated_at TIMESTAMP,
                           pre_sto_status VARCHAR2(10),
                           pre_sto_break_start_time NUMBER,
                           pre_sto_break_time NUMBER,
                           pre_sto_opening_hours VARCHAR2(100),
                           pre_sto_day_off VARCHAR2(100),
                           pre_sto_delivery_area VARCHAR2(200),
                           pre_sto_operating_days VARCHAR2(100),
                           pre_sto_holi_day_week VARCHAR2(100)
);

CREATE TABLE pre_store_photo (
                                 pre_sto_photo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 pre_sto_photo_store_id NUMBER NOT NULL,
                                 pre_sto_photo_url VARCHAR2(300) NOT NULL,
                                 pre_sto_photo_created_at TIMESTAMP,
                                 pre_sto_photo_updated_at TIMESTAMP
);

CREATE TABLE pre_store_menu (
                                menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                pre_sto_id NUMBER NOT NULL,
                                menu_category VARCHAR2(100) NOT NULL,
                                menu_name VARCHAR2(255) NOT NULL,
                                menu_price NUMBER NOT NULL,
                                menu_picture_url VARCHAR2(255) NOT NULL,
                                menu_popularity NUMBER NOT NULL,
                                menu_created_date TIMESTAMP,
                                menu_modified_date TIMESTAMP,
                                menu_status VARCHAR2(10),
                                menu_description VARCHAR2(255)
);

CREATE TABLE reward (
                        reward_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_id NUMBER,
                        reward_amount NUMBER
);

CREATE TABLE login_history (
                               his_login_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               his_mid NUMBER NOT NULL,
                               his_login_date TIMESTAMP DEFAULT SYSDATE NOT NULL,
                               his_ip_address VARCHAR2(45),
                               his_device_os VARCHAR2(50),
                               his_browser VARCHAR2(50)
);

CREATE TABLE delivery_address (
                                  addr_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  addr_member_id NUMBER NOT NULL,
                                  addr_name VARCHAR2(255) NOT NULL,
                                  addr_address VARCHAR2(255) NOT NULL,
                                  addr_is_main VARCHAR2(10) DEFAULT '서브' NOT NULL,
                                  addr_register_date TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE delivery_group (
                                delivery_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                rider_no NUMBER NOT NULL,
                                store_id NUMBER NOT NULL,
                                delivery_type VARCHAR2(20) NOT NULL,
                                delivery_status VARCHAR2(50) NOT NULL,
                                customer_request VARCHAR2(500),
                                delivery_fee NUMBER,
                                created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                                updated_at TIMESTAMP,
                                call_time TIMESTAMP
);

CREATE TABLE cart (
                      cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      mem_id NUMBER NOT NULL,
                      menu_id NUMBER NOT NULL,
                      cart_name VARCHAR2(255),
                      cart_img_url VARCHAR2(255),
                      cart_item_price NUMBER,
                      cart_quantity NUMBER
);

CREATE TABLE orders (
                        order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        pre_sto_id NUMBER NOT NULL,
                        mem_id NUMBER NOT NULL,
                        menu_id NUMBER NOT NULL,
                        order_status NVARCHAR2(20) DEFAULT '주문접수',
                        order_total_price NUMBER,
                        customer_message VARCHAR2(500),
                        delivery_message VARCHAR2(500),
                        payment_method VARCHAR2(255),
                        delivery_type VARCHAR2(255),
                        delivery_status VARCHAR2(255),
                        delivery_fee NUMBER,
                        order_created_at TIMESTAMP DEFAULT SYSDATE,
                        order_updated_at TIMESTAMP,
                        discount_amount NUMBER
);

CREATE TABLE orderitem (
                           order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           order_id NUMBER NOT NULL,
                           menu_id NUMBER NOT NULL,
                           item_name VARCHAR2(255) NOT NULL,
                           quantity NUMBER NOT NULL,
                           item_price NUMBER NOT NULL,
                           total_price NUMBER NOT NULL,
                           order_date TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE reviews (
                         review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         order_id NUMBER NOT NULL,
                         pre_sto_id NUMBER NOT NULL,
                         mem_id NUMBER NOT NULL,
                         menu_id NUMBER NOT NULL,
                         review_rating NUMBER NOT NULL,
                         review_content VARCHAR2(1000) NOT NULL,
                         review_image VARCHAR2(500),
                         review_created_at TIMESTAMP NOT NULL,
                         review_update_at TIMESTAMP
);

CREATE TABLE comments (
                          comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          pre_mem_id NUMBER NOT NULL,
                          review_id NUMBER NOT NULL,
                          board_id NUMBER NOT NULL,
                          admin_id NUMBER NOT NULL,
                          comment_contents VARCHAR2(1000),
                          comment_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE coupon_usages (
                               usage_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               cpn_id NUMBER NOT NULL,
                               mem_id NUMBER,
                               used_at TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE delivery_group_item (
                                     delivery_id NUMBER NOT NULL,
                                     order_id NUMBER NOT NULL,
                                     order_sequence NUMBER,
                                     store_address VARCHAR2(255),
                                     destination_address VARCHAR2(255),
                                     CONSTRAINT pk_delivery_group_item PRIMARY KEY (delivery_id, order_id)
);

CREATE TABLE rider_account (
                               rider_aid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               rider_No NUMBER,
                               rider_bank_name VARCHAR2(255),
                               rider_account_number VARCHAR2(255),
                               rider_account_holder VARCHAR2(255)
);
