/* =========================
   DROP TRIGGER
========================= */

DROP TRIGGER trg_pre_store_update;
DROP TRIGGER trg_orders_update;
DROP TRIGGER trg_pre_store_menu_update;
DROP TRIGGER trg_reviews_update;
DROP TRIGGER trg_pre_member_update;
DROP TRIGGER trg_pre_store_photo_update;
DROP TRIGGER trg_delivery_group_update;
DROP TRIGGER trg_advertisements_update;
DROP TRIGGER trg_coupons_update;


/* =========================
   DROP INDEX
========================= */

DROP INDEX idx_orders_mem_id;
DROP INDEX idx_orders_pre_sto_id;
DROP INDEX idx_orders_menu_id;

DROP INDEX idx_cart_mem_id;
DROP INDEX idx_cart_menu_id;

DROP INDEX idx_reviews_mem_id;
DROP INDEX idx_reviews_pre_sto_id;
DROP INDEX idx_reviews_order_id;

DROP INDEX idx_pre_store_menu_store_id;

DROP INDEX idx_login_history_his_mid;

DROP INDEX idx_delivery_group_rider_no;
DROP INDEX idx_delivery_group_item_order_id;

DROP INDEX idx_coupon_usages_mem_id;

DROP INDEX idx_comments_board_id;
DROP INDEX idx_comments_review_id;


/* =========================
   DROP TABLE - 삭제 순서
   자식 테이블 먼저 삭제
========================= */

DROP TABLE delivery_group_item CASCADE CONSTRAINTS;
DROP TABLE rider_account CASCADE CONSTRAINTS;
DROP TABLE coupon_usages CASCADE CONSTRAINTS;
DROP TABLE comments CASCADE CONSTRAINTS;
DROP TABLE reviews CASCADE CONSTRAINTS;
DROP TABLE orderitem CASCADE CONSTRAINTS;
DROP TABLE orders CASCADE CONSTRAINTS;
DROP TABLE cart CASCADE CONSTRAINTS;
DROP TABLE delivery_group CASCADE CONSTRAINTS;
DROP TABLE delivery_address CASCADE CONSTRAINTS;
DROP TABLE login_history CASCADE CONSTRAINTS;
DROP TABLE reward CASCADE CONSTRAINTS;
DROP TABLE pre_store_menu CASCADE CONSTRAINTS;
DROP TABLE pre_store_photo CASCADE CONSTRAINTS;
DROP TABLE pre_store CASCADE CONSTRAINTS;
DROP TABLE coupons CASCADE CONSTRAINTS;
DROP TABLE boards CASCADE CONSTRAINTS;
DROP TABLE notifications CASCADE CONSTRAINTS;
DROP TABLE riders CASCADE CONSTRAINTS;
DROP TABLE pre_member CASCADE CONSTRAINTS;
DROP TABLE member CASCADE CONSTRAINTS;
DROP TABLE advertisements CASCADE CONSTRAINTS;
DROP TABLE admin CASCADE CONSTRAINTS;

/* =========================
   CREATE TABLE - 생성 순서
   부모 테이블 먼저 생성
========================= */

CREATE TABLE admin (
                       admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       admin_username VARCHAR2(50) NOT NULL UNIQUE,
                       admin_password VARCHAR2(255) NOT NULL,
                       admin_email VARCHAR2(100) NOT NULL UNIQUE,
                       admin_role VARCHAR2(20) DEFAULT '관리자' NOT NULL,
                       admin_created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                       admin_last_login TIMESTAMP,
                       admin_status VARCHAR2(10) DEFAULT '활성' NOT NULL
);

CREATE TABLE advertisements (
                                adv_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                adv_order NUMBER NOT NULL UNIQUE,
                                adv_title VARCHAR2(100),
                                adv_image_url VARCHAR2(255),
                                adv_created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                                adv_updated_at TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE member (
                        mem_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_userid VARCHAR2(100) NOT NULL UNIQUE,
                        mem_email VARCHAR2(255) NOT NULL,
                        mem_password VARCHAR2(255),
                        mem_username VARCHAR2(100) NOT NULL,
                        mem_nickname VARCHAR2(100),
                        mem_phone VARCHAR2(20),
                        mem_birthday DATE,
                        mem_gender VARCHAR2(10),
                        mem_point NUMBER(10) DEFAULT 0 NOT NULL,
                        mem_grade VARCHAR2(10) NOT NULL,
                        mem_address VARCHAR2(255),
                        mem_register_ip VARCHAR2(50) NOT NULL,
                        mem_lastlogin_ip VARCHAR2(50),
                        mem_register_date TIMESTAMP DEFAULT SYSDATE,
                        mem_lastlogin_date TIMESTAMP DEFAULT SYSDATE,
                        mem_status VARCHAR2(10) NOT NULL,
                        mem_receive_email VARCHAR2(10) NOT NULL,
                        mem_open_profile VARCHAR2(10) NOT NULL,
                        mem_receive_notify VARCHAR2(10) NOT NULL,
                        mem_login_type VARCHAR2(20)
);

CREATE TABLE pre_member (
                            pre_mem_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            pre_mem_biz_reg_no VARCHAR2(30) NOT NULL,
                            pre_mem_ceo_name VARCHAR2(50) NOT NULL,
                            pre_mem_phone VARCHAR2(20),
                            pre_mem_user_id VARCHAR2(50) NOT NULL,
                            pre_mem_password VARCHAR2(200) NOT NULL,
                            pre_mem_email VARCHAR2(100) NOT NULL,
                            pre_mem_biz_license_photo VARCHAR2(300),
                            pre_mem_created_at TIMESTAMP,
                            pre_mem_updated_at TIMESTAMP,
                            pre_mem_status VARCHAR2(10),
                            pre_mem_approval_status VARCHAR2(10)
);

CREATE TABLE riders (
                        rider_No NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        rider_id VARCHAR2(50) NOT NULL UNIQUE,
                        rider_pw VARCHAR2(100),
                        rider_name VARCHAR2(50),
                        rider_phone VARCHAR2(20),
                        vehicle_type VARCHAR2(20),
                        rider_gender VARCHAR2(20),
                        rider_birth DATE,
                        rider_created_at TIMESTAMP,
                        total_deliveries NUMBER,
                        is_available VARCHAR2(10) NOT NULL
);

CREATE TABLE coupons (
                         cpn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         cpn_code VARCHAR2(255) NOT NULL UNIQUE,
                         cpn_name VARCHAR2(255) NOT NULL,
                         cpn_content VARCHAR2(255) NOT NULL,
                         cpn_deduct_price NUMBER NOT NULL,
                         cpn_min_price NUMBER NOT NULL,
                         cpn_order_type VARCHAR2(255) NOT NULL,
                         cpn_status VARCHAR2(255) NOT NULL,
                         cpn_created TIMESTAMP DEFAULT SYSDATE NOT NULL,
                         cpn_modified TIMESTAMP DEFAULT SYSDATE NOT NULL,
                         cpn_expired TIMESTAMP NOT NULL
);

CREATE TABLE boards (
                        board_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_id NUMBER NOT NULL,
                        board_title VARCHAR2(255),
                        board_content VARCHAR2(255),
                        board_createdAt TIMESTAMP DEFAULT SYSDATE,
                        board_updatedAt TIMESTAMP,
                        board_answer_status VARCHAR2(255)
);

CREATE TABLE notifications (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               sender_type VARCHAR2(50),
                               sender_id NUMBER,
                               recipient_type VARCHAR2(50) NOT NULL,
                               recipient_id NUMBER NOT NULL,
                               category VARCHAR2(50) NOT NULL,
                               message VARCHAR2(255) NOT NULL,
                               created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                               status VARCHAR2(50) DEFAULT '읽지 않음' NOT NULL
);

CREATE TABLE pre_store (
                           pre_sto_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           pre_sto_pre_mem_id NUMBER NOT NULL,
                           pre_sto_name VARCHAR2(100) NOT NULL,
                           pre_sto_category VARCHAR2(50),
                           pre_sto_address VARCHAR2(200),
                           pre_sto_photo VARCHAR2(300),
                           pre_sto_phone VARCHAR2(20),
                           pre_sto_intro VARCHAR2(1000),
                           pre_sto_min_order_amount NUMBER,
                           pre_sto_delivery_fee NUMBER,
                           pre_sto_delivery_time_min NUMBER,
                           pre_sto_delivery_time_max NUMBER,
                           pre_sto_rating NUMBER(3,1) NOT NULL,
                           pre_sto_review_count NUMBER NOT NULL,
                           pre_sto_created_at TIMESTAMP,
                           pre_sto_updated_at TIMESTAMP,
                           pre_sto_status VARCHAR2(10),
                           pre_sto_break_start_time NUMBER,
                           pre_sto_break_time NUMBER,
                           pre_sto_opening_hours VARCHAR2(100),
                           pre_sto_day_off VARCHAR2(100),
                           pre_sto_delivery_area VARCHAR2(200),
                           pre_sto_operating_days VARCHAR2(100),
                           pre_sto_holi_day_week VARCHAR2(100)
);

CREATE TABLE pre_store_photo (
                                 pre_sto_photo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 pre_sto_photo_store_id NUMBER NOT NULL,
                                 pre_sto_photo_url VARCHAR2(300) NOT NULL,
                                 pre_sto_photo_created_at TIMESTAMP,
                                 pre_sto_photo_updated_at TIMESTAMP
);

CREATE TABLE pre_store_menu (
                                menu_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                pre_sto_id NUMBER NOT NULL,
                                menu_category VARCHAR2(100) NOT NULL,
                                menu_name VARCHAR2(255) NOT NULL,
                                menu_price NUMBER NOT NULL,
                                menu_picture_url VARCHAR2(255) NOT NULL,
                                menu_popularity NUMBER NOT NULL,
                                menu_created_date TIMESTAMP,
                                menu_modified_date TIMESTAMP,
                                menu_status VARCHAR2(10),
                                menu_description VARCHAR2(255)
);

CREATE TABLE reward (
                        reward_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mem_id NUMBER,
                        reward_amount NUMBER
);

CREATE TABLE login_history (
                               his_login_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               his_mid NUMBER NOT NULL,
                               his_login_date TIMESTAMP DEFAULT SYSDATE NOT NULL,
                               his_ip_address VARCHAR2(45),
                               his_device_os VARCHAR2(50),
                               his_browser VARCHAR2(50)
);

CREATE TABLE delivery_address (
                                  addr_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  addr_member_id NUMBER NOT NULL,
                                  addr_name VARCHAR2(255) NOT NULL,
                                  addr_address VARCHAR2(255) NOT NULL,
                                  addr_is_main VARCHAR2(10) DEFAULT '서브' NOT NULL,
                                  addr_register_date TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE delivery_group (
                                delivery_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                rider_no NUMBER NOT NULL,
                                store_id NUMBER NOT NULL,
                                delivery_type VARCHAR2(20) NOT NULL,
                                delivery_status VARCHAR2(50) NOT NULL,
                                customer_request VARCHAR2(500),
                                delivery_fee NUMBER,
                                created_at TIMESTAMP DEFAULT SYSDATE NOT NULL,
                                updated_at TIMESTAMP,
                                call_time TIMESTAMP
);

CREATE TABLE cart (
                      cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      mem_id NUMBER NOT NULL,
                      menu_id NUMBER NOT NULL,
                      cart_name VARCHAR2(255),
                      cart_img_url VARCHAR2(255),
                      cart_item_price NUMBER,
                      cart_quantity NUMBER
);

CREATE TABLE orders (
                        order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        pre_sto_id NUMBER NOT NULL,
                        mem_id NUMBER NOT NULL,
                        menu_id NUMBER NOT NULL,
                        order_status NVARCHAR2(20) DEFAULT '주문접수',
                        order_total_price NUMBER,
                        customer_message VARCHAR2(500),
                        delivery_message VARCHAR2(500),
                        payment_method VARCHAR2(255),
                        delivery_type VARCHAR2(255),
                        delivery_status VARCHAR2(255),
                        delivery_fee NUMBER,
                        order_created_at TIMESTAMP DEFAULT SYSDATE,
                        order_updated_at TIMESTAMP,
                        discount_amount NUMBER
);

CREATE TABLE orderitem (
                           order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           order_id NUMBER NOT NULL,
                           menu_id NUMBER NOT NULL,
                           item_name VARCHAR2(255) NOT NULL,
                           quantity NUMBER NOT NULL,
                           item_price NUMBER NOT NULL,
                           total_price NUMBER NOT NULL,
                           order_date TIMESTAMP DEFAULT SYSDATE
);

CREATE TABLE reviews (
                         review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         order_id NUMBER NOT NULL,
                         pre_sto_id NUMBER NOT NULL,
                         mem_id NUMBER NOT NULL,
                         menu_id NUMBER NOT NULL,
                         review_rating NUMBER NOT NULL,
                         review_content VARCHAR2(1000) NOT NULL,
                         review_image VARCHAR2(500),
                         review_created_at TIMESTAMP NOT NULL,
                         review_update_at TIMESTAMP
);

CREATE TABLE comments (
                          comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          pre_mem_id NUMBER NOT NULL,
                          review_id NUMBER NOT NULL,
                          board_id NUMBER NOT NULL,
                          admin_id NUMBER NOT NULL,
                          comment_contents VARCHAR2(1000),
                          comment_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE coupon_usages (
                               usage_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               cpn_id NUMBER NOT NULL,
                               mem_id NUMBER,
                               used_at TIMESTAMP DEFAULT SYSDATE NOT NULL
);

CREATE TABLE delivery_group_item (
                                     delivery_id NUMBER NOT NULL,
                                     order_id NUMBER NOT NULL,
                                     order_sequence NUMBER,
                                     store_address VARCHAR2(255),
                                     destination_address VARCHAR2(255),
                                     CONSTRAINT pk_delivery_group_item PRIMARY KEY (delivery_id, order_id)
);

CREATE TABLE rider_account (
                               rider_aid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               rider_No NUMBER,
                               rider_bank_name VARCHAR2(255),
                               rider_account_number VARCHAR2(255),
                               rider_account_holder VARCHAR2(255)
);

/* =========================================================
   ADMIN
========================================================= */

COMMENT ON TABLE admin IS '관리자';

COMMENT ON COLUMN admin.admin_id IS '관리자 PK';
COMMENT ON COLUMN admin.admin_username IS '관리자 아이디';
COMMENT ON COLUMN admin.admin_password IS '관리자 비밀번호';
COMMENT ON COLUMN admin.admin_email IS '관리자 이메일';
COMMENT ON COLUMN admin.admin_role IS '관리자 권한';
COMMENT ON COLUMN admin.admin_created_at IS '생성일';
COMMENT ON COLUMN admin.admin_last_login IS '마지막 로그인';
COMMENT ON COLUMN admin.admin_status IS '상태';


/* =========================================================
   ADVERTISEMENTS
========================================================= */

COMMENT ON TABLE advertisements IS '광고';

COMMENT ON COLUMN advertisements.adv_id IS '광고 PK';
COMMENT ON COLUMN advertisements.adv_order IS '광고 순서';
COMMENT ON COLUMN advertisements.adv_title IS '광고 제목';
COMMENT ON COLUMN advertisements.adv_image_url IS '광고 이미지';
COMMENT ON COLUMN advertisements.adv_created_at IS '생성일';
COMMENT ON COLUMN advertisements.adv_updated_at IS '수정일';


/* =========================================================
   MEMBER
========================================================= */

COMMENT ON TABLE member IS '회원';

COMMENT ON COLUMN member.mem_id IS '회원 PK';
COMMENT ON COLUMN member.mem_userid IS '회원 아이디';
COMMENT ON COLUMN member.mem_email IS '회원 이메일';
COMMENT ON COLUMN member.mem_password IS '회원 비밀번호';
COMMENT ON COLUMN member.mem_username IS '회원 이름';
COMMENT ON COLUMN member.mem_nickname IS '닉네임';
COMMENT ON COLUMN member.mem_phone IS '전화번호';
COMMENT ON COLUMN member.mem_birthday IS '생년월일';
COMMENT ON COLUMN member.mem_gender IS '성별';
COMMENT ON COLUMN member.mem_point IS '포인트';
COMMENT ON COLUMN member.mem_grade IS '회원 등급';
COMMENT ON COLUMN member.mem_address IS '주소';
COMMENT ON COLUMN member.mem_register_ip IS '가입 IP';
COMMENT ON COLUMN member.mem_lastlogin_ip IS '최근 로그인 IP';
COMMENT ON COLUMN member.mem_register_date IS '가입일';
COMMENT ON COLUMN member.mem_lastlogin_date IS '최근 로그인일';
COMMENT ON COLUMN member.mem_status IS '회원 상태';
COMMENT ON COLUMN member.mem_receive_email IS '이메일 수신 여부';
COMMENT ON COLUMN member.mem_open_profile IS '프로필 공개 여부';
COMMENT ON COLUMN member.mem_receive_notify IS '알림 수신 여부';
COMMENT ON COLUMN member.mem_login_type IS '로그인 타입';


/* =========================================================
   PRE_MEMBER
========================================================= */

COMMENT ON TABLE pre_member IS '사장 회원';

COMMENT ON COLUMN pre_member.pre_mem_id IS '사장 회원 PK';
COMMENT ON COLUMN pre_member.pre_mem_biz_reg_no IS '사업자 등록번호';
COMMENT ON COLUMN pre_member.pre_mem_ceo_name IS '대표자명';
COMMENT ON COLUMN pre_member.pre_mem_phone IS '전화번호';
COMMENT ON COLUMN pre_member.pre_mem_user_id IS '아이디';
COMMENT ON COLUMN pre_member.pre_mem_password IS '비밀번호';
COMMENT ON COLUMN pre_member.pre_mem_email IS '이메일';
COMMENT ON COLUMN pre_member.pre_mem_biz_license_photo IS '사업자 등록증';
COMMENT ON COLUMN pre_member.pre_mem_created_at IS '생성일';
COMMENT ON COLUMN pre_member.pre_mem_updated_at IS '수정일';
COMMENT ON COLUMN pre_member.pre_mem_status IS '상태';
COMMENT ON COLUMN pre_member.pre_mem_approval_status IS '승인 상태';


/* =========================================================
   RIDERS
========================================================= */

COMMENT ON TABLE riders IS '라이더';

COMMENT ON COLUMN riders.rider_No IS '라이더 PK';
COMMENT ON COLUMN riders.rider_id IS '라이더 아이디';
COMMENT ON COLUMN riders.rider_pw IS '비밀번호';
COMMENT ON COLUMN riders.rider_name IS '이름';
COMMENT ON COLUMN riders.rider_phone IS '전화번호';
COMMENT ON COLUMN riders.vehicle_type IS '차량 종류';
COMMENT ON COLUMN riders.rider_gender IS '성별';
COMMENT ON COLUMN riders.rider_birth IS '생년월일';
COMMENT ON COLUMN riders.rider_created_at IS '생성일';
COMMENT ON COLUMN riders.total_deliveries IS '총 배달 수';
COMMENT ON COLUMN riders.is_available IS '배달 가능 여부';


/* =========================================================
   RIDER_ACCOUNT
========================================================= */

COMMENT ON TABLE rider_account IS '라이더 계좌';

COMMENT ON COLUMN rider_account.rider_aid IS '계좌 PK';
COMMENT ON COLUMN rider_account.rider_No IS '라이더 FK';
COMMENT ON COLUMN rider_account.rider_bank_name IS '은행명';
COMMENT ON COLUMN rider_account.rider_account_number IS '계좌번호';
COMMENT ON COLUMN rider_account.rider_account_holder IS '예금주';


/* =========================================================
   PRE_STORE
========================================================= */

COMMENT ON TABLE pre_store IS '가게';

COMMENT ON COLUMN pre_store.pre_sto_id IS '가게 PK';
COMMENT ON COLUMN pre_store.pre_sto_pre_mem_id IS '사장 회원 FK';
COMMENT ON COLUMN pre_store.pre_sto_name IS '가게명';
COMMENT ON COLUMN pre_store.pre_sto_category IS '카테고리';
COMMENT ON COLUMN pre_store.pre_sto_address IS '주소';
COMMENT ON COLUMN pre_store.pre_sto_photo IS '대표 사진';
COMMENT ON COLUMN pre_store.pre_sto_phone IS '전화번호';
COMMENT ON COLUMN pre_store.pre_sto_intro IS '소개';
COMMENT ON COLUMN pre_store.pre_sto_min_order_amount IS '최소 주문 금액';
COMMENT ON COLUMN pre_store.pre_sto_delivery_fee IS '배달비';
COMMENT ON COLUMN pre_store.pre_sto_delivery_time_min IS '최소 배달 시간';
COMMENT ON COLUMN pre_store.pre_sto_delivery_time_max IS '최대 배달 시간';
COMMENT ON COLUMN pre_store.pre_sto_rating IS '평점';
COMMENT ON COLUMN pre_store.pre_sto_review_count IS '리뷰 수';
COMMENT ON COLUMN pre_store.pre_sto_created_at IS '생성일';
COMMENT ON COLUMN pre_store.pre_sto_updated_at IS '수정일';
COMMENT ON COLUMN pre_store.pre_sto_status IS '상태';


/* =========================================================
   PRE_STORE_PHOTO
========================================================= */

COMMENT ON TABLE pre_store_photo IS '가게 사진';

COMMENT ON COLUMN pre_store_photo.pre_sto_photo_id IS '사진 PK';
COMMENT ON COLUMN pre_store_photo.pre_sto_photo_store_id IS '가게 FK';
COMMENT ON COLUMN pre_store_photo.pre_sto_photo_url IS '사진 URL';
COMMENT ON COLUMN pre_store_photo.pre_sto_photo_created_at IS '생성일';
COMMENT ON COLUMN pre_store_photo.pre_sto_photo_updated_at IS '수정일';


/* =========================================================
   PRE_STORE_MENU
========================================================= */

COMMENT ON TABLE pre_store_menu IS '가게 메뉴';

COMMENT ON COLUMN pre_store_menu.menu_id IS '메뉴 PK';
COMMENT ON COLUMN pre_store_menu.pre_sto_id IS '가게 FK';
COMMENT ON COLUMN pre_store_menu.menu_category IS '메뉴 카테고리';
COMMENT ON COLUMN pre_store_menu.menu_name IS '메뉴명';
COMMENT ON COLUMN pre_store_menu.menu_price IS '가격';
COMMENT ON COLUMN pre_store_menu.menu_picture_url IS '메뉴 사진';
COMMENT ON COLUMN pre_store_menu.menu_popularity IS '인기 여부';
COMMENT ON COLUMN pre_store_menu.menu_created_date IS '생성일';
COMMENT ON COLUMN pre_store_menu.menu_modified_date IS '수정일';
COMMENT ON COLUMN pre_store_menu.menu_status IS '상태';
COMMENT ON COLUMN pre_store_menu.menu_description IS '메뉴 설명';


/* =========================================================
   CART
========================================================= */

COMMENT ON TABLE cart IS '장바구니';

COMMENT ON COLUMN cart.cart_id IS '장바구니 PK';
COMMENT ON COLUMN cart.mem_id IS '회원 FK';
COMMENT ON COLUMN cart.menu_id IS '메뉴 FK';
COMMENT ON COLUMN cart.cart_name IS '메뉴명';
COMMENT ON COLUMN cart.cart_img_url IS '메뉴 이미지';
COMMENT ON COLUMN cart.cart_item_price IS '가격';
COMMENT ON COLUMN cart.cart_quantity IS '수량';


/* =========================================================
   ORDERS
========================================================= */

COMMENT ON TABLE orders IS '주문';

COMMENT ON COLUMN orders.order_id IS '주문 PK';
COMMENT ON COLUMN orders.pre_sto_id IS '가게 FK';
COMMENT ON COLUMN orders.mem_id IS '회원 FK';
COMMENT ON COLUMN orders.menu_id IS '메뉴 FK';
COMMENT ON COLUMN orders.order_status IS '주문 상태';
COMMENT ON COLUMN orders.order_total_price IS '총 금액';
COMMENT ON COLUMN orders.customer_message IS '고객 요청사항';
COMMENT ON COLUMN orders.delivery_message IS '배달 요청사항';
COMMENT ON COLUMN orders.payment_method IS '결제 방식';
COMMENT ON COLUMN orders.delivery_type IS '배달 유형';
COMMENT ON COLUMN orders.delivery_status IS '배달 상태';
COMMENT ON COLUMN orders.delivery_fee IS '배달비';
COMMENT ON COLUMN orders.order_created_at IS '생성일';
COMMENT ON COLUMN orders.order_updated_at IS '수정일';
COMMENT ON COLUMN orders.discount_amount IS '할인 금액';


/* =========================================================
   ORDERITEM
========================================================= */

COMMENT ON TABLE orderitem IS '주문 상품';

COMMENT ON COLUMN orderitem.order_item_id IS '주문 상품 PK';
COMMENT ON COLUMN orderitem.order_id IS '주문 FK';
COMMENT ON COLUMN orderitem.menu_id IS '메뉴 FK';
COMMENT ON COLUMN orderitem.item_name IS '상품명';
COMMENT ON COLUMN orderitem.quantity IS '수량';
COMMENT ON COLUMN orderitem.item_price IS '상품 가격';
COMMENT ON COLUMN orderitem.total_price IS '총 가격';
COMMENT ON COLUMN orderitem.order_date IS '주문일';


/* =========================================================
   REVIEWS
========================================================= */

COMMENT ON TABLE reviews IS '리뷰';

COMMENT ON COLUMN reviews.review_id IS '리뷰 PK';
COMMENT ON COLUMN reviews.order_id IS '주문 FK';
COMMENT ON COLUMN reviews.pre_sto_id IS '가게 FK';
COMMENT ON COLUMN reviews.mem_id IS '회원 FK';
COMMENT ON COLUMN reviews.menu_id IS '메뉴 FK';
COMMENT ON COLUMN reviews.review_rating IS '평점';
COMMENT ON COLUMN reviews.review_content IS '리뷰 내용';
COMMENT ON COLUMN reviews.review_image IS '리뷰 이미지';
COMMENT ON COLUMN reviews.review_created_at IS '생성일';
COMMENT ON COLUMN reviews.review_update_at IS '수정일';


/* =========================================================
   COMMENTS
========================================================= */

COMMENT ON TABLE comments IS '댓글';

COMMENT ON COLUMN comments.comment_id IS '댓글 PK';
COMMENT ON COLUMN comments.pre_mem_id IS '사장 회원 FK';
COMMENT ON COLUMN comments.review_id IS '리뷰 FK';
COMMENT ON COLUMN comments.board_id IS '게시글 FK';
COMMENT ON COLUMN comments.admin_id IS '관리자 FK';
COMMENT ON COLUMN comments.comment_contents IS '댓글 내용';
COMMENT ON COLUMN comments.comment_date IS '작성일';


/* =========================================================
   COUPONS
========================================================= */

COMMENT ON TABLE coupons IS '쿠폰';

COMMENT ON COLUMN coupons.cpn_id IS '쿠폰 PK';
COMMENT ON COLUMN coupons.cpn_code IS '쿠폰 코드';
COMMENT ON COLUMN coupons.cpn_name IS '쿠폰명';
COMMENT ON COLUMN coupons.cpn_content IS '쿠폰 설명';
COMMENT ON COLUMN coupons.cpn_deduct_price IS '할인 금액';
COMMENT ON COLUMN coupons.cpn_min_price IS '최소 주문 금액';
COMMENT ON COLUMN coupons.cpn_order_type IS '주문 타입';
COMMENT ON COLUMN coupons.cpn_status IS '쿠폰 상태';
COMMENT ON COLUMN coupons.cpn_created IS '생성일';
COMMENT ON COLUMN coupons.cpn_modified IS '수정일';
COMMENT ON COLUMN coupons.cpn_expired IS '만료일';


/* =========================================================
   COUPON_USAGES
========================================================= */

COMMENT ON TABLE coupon_usages IS '쿠폰 사용 이력';

COMMENT ON COLUMN coupon_usages.usage_id IS '사용 이력 PK';
COMMENT ON COLUMN coupon_usages.cpn_id IS '쿠폰 FK';
COMMENT ON COLUMN coupon_usages.mem_id IS '회원 FK';
COMMENT ON COLUMN coupon_usages.used_at IS '사용일';


/* =========================================================
   LOGIN_HISTORY
========================================================= */

COMMENT ON TABLE login_history IS '로그인 기록';

COMMENT ON COLUMN login_history.his_login_id IS '로그인 기록 PK';
COMMENT ON COLUMN login_history.his_mid IS '회원 FK';
COMMENT ON COLUMN login_history.his_login_date IS '로그인 일시';
COMMENT ON COLUMN login_history.his_ip_address IS 'IP 주소';
COMMENT ON COLUMN login_history.his_device_os IS '운영체제';
COMMENT ON COLUMN login_history.his_browser IS '브라우저';


/* =========================================================
   DELIVERY_ADDRESS
========================================================= */

COMMENT ON TABLE delivery_address IS '배송지';

COMMENT ON COLUMN delivery_address.addr_id IS '배송지 PK';
COMMENT ON COLUMN delivery_address.addr_member_id IS '회원 FK';
COMMENT ON COLUMN delivery_address.addr_name IS '배송지명';
COMMENT ON COLUMN delivery_address.addr_address IS '주소';
COMMENT ON COLUMN delivery_address.addr_is_main IS '기본 배송지 여부';
COMMENT ON COLUMN delivery_address.addr_register_date IS '등록일';


/* =========================================================
   DELIVERY_GROUP
========================================================= */

COMMENT ON TABLE delivery_group IS '배달 그룹';

COMMENT ON COLUMN delivery_group.delivery_id IS '배달 그룹 PK';
COMMENT ON COLUMN delivery_group.rider_no IS '라이더 FK';
COMMENT ON COLUMN delivery_group.store_id IS '가게 FK';
COMMENT ON COLUMN delivery_group.delivery_type IS '배달 유형';
COMMENT ON COLUMN delivery_group.delivery_status IS '배달 상태';
COMMENT ON COLUMN delivery_group.customer_request IS '고객 요청사항';
COMMENT ON COLUMN delivery_group.delivery_fee IS '배달비';
COMMENT ON COLUMN delivery_group.created_at IS '생성일';
COMMENT ON COLUMN delivery_group.updated_at IS '수정일';
COMMENT ON COLUMN delivery_group.call_time IS '배차 시간';


/* =========================================================
   DELIVERY_GROUP_ITEM
========================================================= */

COMMENT ON TABLE delivery_group_item IS '배달 그룹 상세';

COMMENT ON COLUMN delivery_group_item.delivery_id IS '배달 그룹 FK';
COMMENT ON COLUMN delivery_group_item.order_id IS '주문 FK';
COMMENT ON COLUMN delivery_group_item.order_sequence IS '배달 순서';
COMMENT ON COLUMN delivery_group_item.store_address IS '가게 주소';
COMMENT ON COLUMN delivery_group_item.destination_address IS '목적지 주소';


/* =========================================================
   NOTIFICATIONS
========================================================= */

COMMENT ON TABLE notifications IS '알림';

COMMENT ON COLUMN notifications.id IS '알림 PK';
COMMENT ON COLUMN notifications.sender_type IS '발신자 타입';
COMMENT ON COLUMN notifications.sender_id IS '발신자 ID';
COMMENT ON COLUMN notifications.recipient_type IS '수신자 타입';
COMMENT ON COLUMN notifications.recipient_id IS '수신자 ID';
COMMENT ON COLUMN notifications.category IS '알림 카테고리';
COMMENT ON COLUMN notifications.message IS '알림 메시지';
COMMENT ON COLUMN notifications.created_at IS '생성일';
COMMENT ON COLUMN notifications.status IS '읽음 상태';


/* =========================================================
   REWARD
========================================================= */

COMMENT ON TABLE reward IS '리워드';

COMMENT ON COLUMN reward.reward_id IS '리워드 PK';
COMMENT ON COLUMN reward.mem_id IS '회원 FK';
COMMENT ON COLUMN reward.reward_amount IS '리워드 금액';


/* =========================================================
   BOARDS
========================================================= */

COMMENT ON TABLE boards IS '게시판';

COMMENT ON COLUMN boards.board_id IS '게시글 PK';
COMMENT ON COLUMN boards.mem_id IS '회원 FK';
COMMENT ON COLUMN boards.board_title IS '제목';
COMMENT ON COLUMN boards.board_content IS '내용';
COMMENT ON COLUMN boards.board_createdAt IS '생성일';
COMMENT ON COLUMN boards.board_updatedAt IS '수정일';
COMMENT ON COLUMN boards.board_answer_status IS '답변 상태';

        /* =========================================================
   FK CONSTRAINT
========================================================= */

/* LOGIN_HISTORY */
ALTER TABLE login_history
    ADD CONSTRAINT fk_login_history_member
        FOREIGN KEY (his_mid)
            REFERENCES member(mem_id);

/* REWARD */
ALTER TABLE reward
    ADD CONSTRAINT fk_reward_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

/* DELIVERY_ADDRESS */
ALTER TABLE delivery_address
    ADD CONSTRAINT fk_delivery_address_member
        FOREIGN KEY (addr_member_id)
            REFERENCES member(mem_id);

/* PRE_STORE */
ALTER TABLE pre_store
    ADD CONSTRAINT fk_pre_store_pre_member
        FOREIGN KEY (pre_sto_pre_mem_id)
            REFERENCES pre_member(pre_mem_id);

/* PRE_STORE_PHOTO */
ALTER TABLE pre_store_photo
    ADD CONSTRAINT fk_pre_store_photo_store
        FOREIGN KEY (pre_sto_photo_store_id)
            REFERENCES pre_store(pre_sto_id);

/* PRE_STORE_MENU */
ALTER TABLE pre_store_menu
    ADD CONSTRAINT fk_pre_store_menu_store
        FOREIGN KEY (pre_sto_id)
            REFERENCES pre_store(pre_sto_id);

/* CART */
ALTER TABLE cart
    ADD CONSTRAINT fk_cart_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

ALTER TABLE cart
    ADD CONSTRAINT fk_cart_menu
        FOREIGN KEY (menu_id)
            REFERENCES pre_store_menu(menu_id);

/* ORDERS */
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_store
        FOREIGN KEY (pre_sto_id)
            REFERENCES pre_store(pre_sto_id);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_menu
        FOREIGN KEY (menu_id)
            REFERENCES pre_store_menu(menu_id);

/* ORDERITEM */
ALTER TABLE orderitem
    ADD CONSTRAINT fk_orderitem_order
        FOREIGN KEY (order_id)
            REFERENCES orders(order_id);

ALTER TABLE orderitem
    ADD CONSTRAINT fk_orderitem_menu
        FOREIGN KEY (menu_id)
            REFERENCES pre_store_menu(menu_id);

/* REVIEWS */
ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_order
        FOREIGN KEY (order_id)
            REFERENCES orders(order_id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_store
        FOREIGN KEY (pre_sto_id)
            REFERENCES pre_store(pre_sto_id);

ALTER TABLE reviews
    ADD CONSTRAINT fk_reviews_menu
        FOREIGN KEY (menu_id)
            REFERENCES pre_store_menu(menu_id);

/* COMMENTS */
ALTER TABLE comments
    ADD CONSTRAINT fk_comments_admin
        FOREIGN KEY (admin_id)
            REFERENCES admin(admin_id);

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_board
        FOREIGN KEY (board_id)
            REFERENCES boards(board_id);

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_review
        FOREIGN KEY (review_id)
            REFERENCES reviews(review_id);

ALTER TABLE comments
    ADD CONSTRAINT fk_comments_pre_member
        FOREIGN KEY (pre_mem_id)
            REFERENCES pre_member(pre_mem_id);

/* COUPON_USAGES */
ALTER TABLE coupon_usages
    ADD CONSTRAINT fk_coupon_usages_coupon
        FOREIGN KEY (cpn_id)
            REFERENCES coupons(cpn_id);

ALTER TABLE coupon_usages
    ADD CONSTRAINT fk_coupon_usages_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

/* DELIVERY_GROUP */
ALTER TABLE delivery_group
    ADD CONSTRAINT fk_delivery_group_rider
        FOREIGN KEY (rider_no)
            REFERENCES riders(rider_No);

ALTER TABLE delivery_group
    ADD CONSTRAINT fk_delivery_group_store
        FOREIGN KEY (store_id)
            REFERENCES pre_store(pre_sto_id);

/* DELIVERY_GROUP_ITEM */
ALTER TABLE delivery_group_item
    ADD CONSTRAINT fk_delivery_group_item_delivery
        FOREIGN KEY (delivery_id)
            REFERENCES delivery_group(delivery_id);

ALTER TABLE delivery_group_item
    ADD CONSTRAINT fk_delivery_group_item_order
        FOREIGN KEY (order_id)
            REFERENCES orders(order_id);

/* RIDER_ACCOUNT */
ALTER TABLE rider_account
    ADD CONSTRAINT fk_rider_account_rider
        FOREIGN KEY (rider_No)
            REFERENCES riders(rider_No);

ALTER TABLE boards
    ADD CONSTRAINT fk_boards_member
        FOREIGN KEY (mem_id)
            REFERENCES member(mem_id);

CREATE INDEX idx_boards_mem_id
    ON boards(mem_id);

/* =========================================================
   INDEX
========================================================= */

CREATE INDEX idx_orders_mem_id
    ON orders(mem_id);

CREATE INDEX idx_orders_pre_sto_id
    ON orders(pre_sto_id);

CREATE INDEX idx_orders_menu_id
    ON orders(menu_id);

CREATE INDEX idx_cart_mem_id
    ON cart(mem_id);

CREATE INDEX idx_cart_menu_id
    ON cart(menu_id);

CREATE INDEX idx_reviews_mem_id
    ON reviews(mem_id);

CREATE INDEX idx_reviews_pre_sto_id
    ON reviews(pre_sto_id);

CREATE INDEX idx_reviews_order_id
    ON reviews(order_id);

CREATE INDEX idx_pre_store_menu_store_id
    ON pre_store_menu(pre_sto_id);

CREATE INDEX idx_login_history_his_mid
    ON login_history(his_mid);

CREATE INDEX idx_delivery_group_rider_no
    ON delivery_group(rider_no);

CREATE INDEX idx_delivery_group_item_order_id
    ON delivery_group_item(order_id);

CREATE INDEX idx_coupon_usages_mem_id
    ON coupon_usages(mem_id);

CREATE INDEX idx_comments_board_id
    ON comments(board_id);

CREATE INDEX idx_comments_review_id
    ON comments(review_id);



/* =========================================================
   UPDATED_AT TRIGGER
========================================================= */

CREATE OR REPLACE TRIGGER trg_pre_store_update
BEFORE UPDATE ON pre_store
                  FOR EACH ROW
BEGIN
    :NEW.pre_sto_updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_orders_update
BEFORE UPDATE ON orders
                  FOR EACH ROW
BEGIN
    :NEW.order_updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_pre_store_menu_update
BEFORE UPDATE ON pre_store_menu
                  FOR EACH ROW
BEGIN
    :NEW.menu_modified_date := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_reviews_update
BEFORE UPDATE ON reviews
                  FOR EACH ROW
BEGIN
    :NEW.review_update_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_pre_member_update
BEFORE UPDATE ON pre_member
                  FOR EACH ROW
BEGIN
    :NEW.pre_mem_updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_pre_store_photo_update
BEFORE UPDATE ON pre_store_photo
                  FOR EACH ROW
BEGIN
    :NEW.pre_sto_photo_updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_delivery_group_update
BEFORE UPDATE ON delivery_group
                  FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_advertisements_update
BEFORE UPDATE ON advertisements
                  FOR EACH ROW
BEGIN
    :NEW.adv_updated_at := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER trg_coupons_update
BEFORE UPDATE ON coupons
                  FOR EACH ROW
BEGIN
    :NEW.cpn_modified := SYSDATE;
END;
/



/* =========================================================
   SAMPLE INSERT
========================================================= */

/* ADMIN */
INSERT INTO admin (
    admin_username,
    admin_password,
    admin_email
) VALUES (
    'admin',
    '1234',
    'admin@test.com'
);

/* MEMBER */
INSERT INTO member (
    mem_userid,
    mem_email,
    mem_password,
    mem_username,
    mem_register_ip,
    mem_grade,
    mem_status,
    mem_receive_email,
    mem_open_profile,
    mem_receive_notify
) VALUES (
             'user01',
             'user01@test.com',
             '1234',
             '홍길동',
             '127.0.0.1',
             '일반',
             '활성',
             'Y',
             'Y',
             'Y'
         );

/* PRE_MEMBER */
INSERT INTO pre_member (
    pre_mem_biz_reg_no,
    pre_mem_ceo_name,
    pre_mem_user_id,
    pre_mem_password,
    pre_mem_email
) VALUES (
             '123-45-67890',
             '김사장',
             'store01',
             '1234',
             'store01@test.com'
         );

/* RIDERS */
INSERT INTO riders (
    rider_id,
    rider_pw,
    rider_name,
    rider_phone,
    vehicle_type,
    is_available
) VALUES (
             'rider01',
             '1234',
             '박라이더',
             '010-1111-2222',
             '오토바이',
             'Y'
         );

/* PRE_STORE */
INSERT INTO pre_store (
    pre_sto_pre_mem_id,
    pre_sto_name,
    pre_sto_category,
    pre_sto_address,
    pre_sto_phone,
    pre_sto_min_order_amount,
    pre_sto_delivery_fee,
    pre_sto_rating,
    pre_sto_review_count,
    pre_sto_status
) VALUES (
             1,
             '교촌치킨',
             '치킨',
             '인천광역시',
             '032-111-2222',
             15000,
             3000,
             5.0,
             0,
             '운영중'
         );

/* MENU */
INSERT INTO pre_store_menu (
    pre_sto_id,
    menu_category,
    menu_name,
    menu_price,
    menu_picture_url,
    menu_popularity,
    menu_status
) VALUES (
             1,
             '메인메뉴',
             '허니콤보',
             23000,
             '/images/honeycombo.jpg',
             1,
             '판매중'
         );

/* ORDERS */
INSERT INTO orders (
    pre_sto_id,
    mem_id,
    menu_id,
    order_total_price,
    payment_method,
    delivery_fee
) VALUES (
             1,
             1,
             1,
             26000,
             'CARD',
             3000
         );

/* ORDERITEM */
INSERT INTO orderitem (
    order_id,
    menu_id,
    item_name,
    quantity,
    item_price,
    total_price
) VALUES (
             1,
             1,
             '허니콤보',
             1,
             23000,
             23000
         );

/* REVIEW */
INSERT INTO reviews (
    order_id,
    pre_sto_id,
    mem_id,
    menu_id,
    review_rating,
    review_content,
    review_created_at
) VALUES (
             1,
             1,
             1,
             1,
             5,
             '맛있어요',
             SYSDATE
         );

/* =========================================================
   BOARD SAMPLE
========================================================= */

INSERT INTO boards (
    mem_id,
    board_title,
    board_content,
    board_answer_status
) VALUES (
             1,
             '배달 문의',
             '배달이 아직 안왔어요.',
             '대기'
         );


/* =========================================================
   COMMENT SAMPLE
========================================================= */

INSERT INTO comments (
    pre_mem_id,
    review_id,
    board_id,
    admin_id,
    comment_contents
) VALUES (
             1,
             1,
             1,
             1,
             '확인 후 처리하겠습니다.'
         );


/* =========================================================
   COUPON SAMPLE
========================================================= */

INSERT INTO coupons (
    cpn_code,
    cpn_name,
    cpn_content,
    cpn_deduct_price,
    cpn_min_price,
    cpn_order_type,
    cpn_status,
    cpn_expired
) VALUES (
             'WELCOME1000',
             '신규 가입 쿠폰',
             '첫 주문 할인',
             1000,
             15000,
             '배달',
             '활성',
             SYSDATE + 30
         );


/* =========================================================
   COUPON_USAGE SAMPLE
========================================================= */

INSERT INTO coupon_usages (
    cpn_id,
    mem_id,
    used_at
) VALUES (
             1,
             1,
             SYSDATE
         );


/* =========================================================
   DELIVERY_ADDRESS SAMPLE
========================================================= */

INSERT INTO delivery_address (
    addr_member_id,
    addr_name,
    addr_address,
    addr_is_main
) VALUES (
             1,
             '집',
             '인천광역시 미추홀구',
             'Y'
         );


/* =========================================================
   DELIVERY_GROUP SAMPLE
========================================================= */

INSERT INTO delivery_group (
    rider_no,
    store_id,
    delivery_type,
    delivery_status,
    customer_request,
    delivery_fee,
    call_time
) VALUES (
             1,
             1,
             '배달',
             '배차완료',
             '문앞에 놔주세요',
             3000,
             SYSDATE
         );


/* =========================================================
   DELIVERY_GROUP_ITEM SAMPLE
========================================================= */

INSERT INTO delivery_group_item (
    delivery_id,
    order_id,
    order_sequence,
    store_address,
    destination_address
) VALUES (
             1,
             1,
             1,
             '인천광역시 치킨거리',
             '인천광역시 미추홀구'
         );


/* =========================================================
   RIDER_ACCOUNT SAMPLE
========================================================= */

INSERT INTO rider_account (
    rider_no,
    rider_bank_name,
    rider_account_number,
    rider_account_holder
) VALUES (
             1,
             '국민은행',
             '123456-78-999999',
             '박라이더'
         );


/* =========================================================
   ADVERTISEMENT SAMPLE
========================================================= */

INSERT INTO advertisements (
    adv_order,
    adv_title,
    adv_image_url
) VALUES (
             1,
             '치킨 할인 이벤트',
             '/images/event_banner.jpg'
         );


/* =========================================================
   NOTIFICATION SAMPLE
========================================================= */

INSERT INTO notifications (
    sender_type,
    sender_id,
    recipient_type,
    recipient_id,
    category,
    message
) VALUES (
             'SYSTEM',
             1,
             'MEMBER',
             1,
             '주문',
             '주문이 접수되었습니다.'
         );


/* =========================================================
   REWARD SAMPLE
========================================================= */

INSERT INTO reward (
    mem_id,
    reward_amount
) VALUES (
             1,
             3000
         );


/* =========================================================
   PRE_STORE_PHOTO SAMPLE
========================================================= */

INSERT INTO pre_store_photo (
    pre_sto_photo_store_id,
    pre_sto_photo_url
) VALUES (
             1,
             '/images/store_photo.jpg'
         );


/* =========================================================
   LOGIN_HISTORY SAMPLE
========================================================= */

INSERT INTO login_history (
    his_mid,
    his_ip_address,
    his_device_os,
    his_browser
) VALUES (
             1,
             '127.0.0.1',
             'Windows',
             'Chrome'
         );